### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nikteg** [nikteg/chalmersfood#5]
```2017-12-15T09:39:11.349004206Z app[web.1]: /app/src/food.ts:14
2017-12-15T09:39:11.349021038Z app[web.1]:   return (result as RestaurantResultWithError).error != null
2017-12-15T09:39:11.349031095Z app[web.1]:                                                ^
2017-12-15T09:39:11.349059590Z app[web.1]: TypeError: Cannot read property 'error' of undefined
2017-12-15T09:39:11.349070276Z app[web.1]:     at isResultWithError (/app/src/food.ts:14:48)
2017-12-15T09:39:11.349098562Z app[web.1]:     at Object.exports.validResult (/app/src/food.ts:20:7)
2017-12-15T09:39:11.349108829Z app[web.1]:     at cache.data.results.map (/app/src/index.ts:65:45)
2017-12-15T09:39:11.349117489Z app[web.1]:     at Array.map (<anonymous>)
2017-12-15T09:39:11.349128175Z app[web.1]:     at SafeSubscriber.data$.first.subscribe [as _next] (/app/src/index.ts:65:26)
2017-12-15T09:39:11.349138232Z app[web.1]:     at SafeSubscriber.__tryOrUnsub (/app/node_modules/@reactivex/rxjs/dist/src/Subscriber.ts:254:10)
2017-12-15T09:39:11.349149686Z app[web.1]:     at SafeSubscriber.next (/app/node_modules/@reactivex/rxjs/dist/src/Subscriber.ts:204:14)
2017-12-15T09:39:11.349158696Z app[web.1]:     at Subscriber._next (/app/node_modules/@reactivex/rxjs/dist/src/Subscriber.ts:135:22)
2017-12-15T09:39:11.349167636Z app[web.1]:     at Subscriber.next (/app/node_modules/@reactivex/rxjs/dist/src/Subscriber.ts:95:12)
2017-12-15T09:39:11.349176576Z app[web.1]:     at FirstSubscriber._emitFinal (/app/node_modules/@reactivex/rxjs/dist/src/operators/first.ts:151:19)```

**Comment by nikteg** [comment]
Closed in 89d9da26c89495d66c70576b1b6ad48b12792a39
